#!/bin/bash
ulimit -d unlimited
ulimit -s unlimited
ulimit -Sa
ulimit -Ha

CASE=tear_circ_303_tgnum
JOREK_HOME=`readlink -f ${PWD}/../../..` # Assumption about source code location

cd ${JOREK_HOME}
source non_regression_tests/job_scripts/jenkins/env.sh
## Compile with:       
# non_regression_tests/run_test.sh -p $CASE
## Initial Long run: 
#non_regression_tests/run_test.sh -i -k -n $CASE 
## Restart run: 
non_regression_tests/run_test.sh -k -n $CASE 
