#!/bin/bash
# @ job_name = tear_circ_303
# @ class = clallmds+
# @ as_limit = 24gb
# @ error  = $(job_name).$(jobid).err
# @ output = $(job_name).$(jobid).out
# @ environment = COPY_ALL
# @ wall_clock_limit = 0:55:00
# @ job_type = mpich
# @ restart = no
#######################################################################
# Look to non_regression_tests/testcases/tearing_limiter_199
# to determine nb of nodes, MPI processes, and nb of threads
#######################################################################
# @ node = 2
# @ total_tasks = 2
# @ resources = ConsumableCpus(16)
#####################################
# @ node_usage = not_shared
# @ queue

ulimit -d unlimited
ulimit -s unlimited
ulimit -Sa
ulimit -Ha

CASE=tear_circ_303
JOREK_HOME=`readlink -f ${PWD}/../../..` # Assumption about source code location

cd ${JOREK_HOME}
source non_regression_tests/job_scripts/poincare/env.sh
export OMP_NUM_THREADS=16
## Compile with:       
# non_regression_tests/run_test.sh -p $CASE
## Initial Long run: 
#non_regression_tests/run_test.sh -i -k -n $CASE 
## Restart run: 
non_regression_tests/run_test.sh -k -n $CASE 
