!> Module containing the usage help texts
!! (used by jorek2_postproc)
module postproc_help
  
  
  
  implicit none
  
  
  
  contains
  
  
  
  !> Print general usage information
  subroutine general_help()
    
    write(*,*) ''
    write(*,*) '============================================================================'
    write(*,*) 'Help topics:'
    write(*,*) '  getting_started       Very brief introduction by an example'
    write(*,*) '  average               Poloidally and toroidally averaged profiles'
    write(*,*) '  average_h5            Reads several .h5 files and writes an average one'
    write(*,*) '  exit                  Exit the program'
    write(*,*) '  equil_params          Output equilibrim parameters (axis, X-point, limiter)'
    write(*,*) '  energy_spectrum       Output the energy spectrum in a specific time window'
    write(*,*) '  expressions           List or select physical expressions'
    write(*,*) '  expressions_int       List or select physical expressions for integration'
    write(*,*) '  fluxsurfaces          Output flux surfaces'
    write(*,*) '  for                   Loop over one or several timesteps'
    write(*,*) '  four2d                Perform a 2D Fourier analysis'
    write(*,*) '  gourdon               Export magnetic field for Gourdon'
    write(*,*) '  grid                  Output the grid'
    write(*,*) '  help                  Print interactive help information'
    write(*,*) '  I_halo_TPF            Export integral poloidal halo current & TPF (see help)'
    write(*,*) '  int2d                 Calculate various 2D integrals'
    write(*,*) '  int3d                 Calculate various 3D integrals (also bnd integrals)'
    write(*,*) '  int_along_pol_line    Integrate expr. on line from (R0,Z0,phi) to (R1,Z1,phi)'
    write(*,*) '  jnorm_bnd_curr        Exports normal current density to the boundary R,Z pts'
    write(*,*) '  jorek-units           Switch to JOREK normalized units'
    write(*,*) '  mark_coords           Mark expressions as coordinates'
    write(*,*) '  midplane              Toroidally averaged expressions on the midplane'
    write(*,*) '  namelist              Load a namelist input file'
    write(*,*) '  params                Print JOREK parameters'
    write(*,*) '  point                 Expressions at a certain (R,Z,phi) position'
    write(*,*) '  pol_line              Expressions along line from (R0,Z0,phi) to (R1,Z1,phi)'
    write(*,*) '  rectangle             Expressions on a rectangular area in R,Z'
    write(*,*) '  qprofile              Export q-profile versus Psi_N'
    write(*,*) '  q_at_psin             Export q value at a given Psi_N over time'
    write(*,*) '  separatrix            Output the separtrix'
    write(*,*) '  set                   Change a setting or list all postproc settings'
    write(*,*) '  si-units              Switch to SI units'
    write(*,*) '  spi-state             Write out SPI related information'
    write(*,*) '  timesteps             List available restart files'
    write(*,*) '  tor_line              Expressions along line from (R,Z,phi0) to (R,Z,phi1)'
    write(*,*) '----------------------------------------------------------------------------'
    write(*,*) '  Enter "help <command>" for details'
    write(*,*) '============================================================================'
    write(*,*) ''
    
  end subroutine general_help
  
  
  
  !> Print specific help for a certain command
  subroutine specific_help(topic)
    
    character(len=*), intent(in) :: topic !< Print specific help for this help topic
    
    write(*,*) ''
    write(*,*) '========================================================================='
    write(*,*) 'Help topic: ', trim(topic)
    write(*,*) '-------------------------------------------------------------------------'
    select case ( trim(topic) )
      case ( 'getting_started' )
        write(*,*) 'Welcome to the interactive postprocessing tool JOREK2_POSTPROC!'
        write(*,*) ''
        write(*,*) 'An example to get you started:'
        write(*,*) ''
        write(*,*) '  namelist input               # Read namelist input file'
        write(*,*) '  jorek-units                  # Select JOREK units'
        write(*,*) '  for step 100 to 200 do       # Do the following for severl time steps:'
        write(*,*) ''
        write(*,*) '    expressions Psi_N T rho      # Select physical expressions'
        write(*,*) '    mark_coords 1                # Mark first expression as coordinate'
        write(*,*) '    set surfaces 200             # Number of flux surfaces'
        write(*,*) '    average                      # Toroidal and poloidal average'
        write(*,*) ''
        write(*,*) '    expressions R rho T Psi Er   # Select expressions'
        write(*,*) '    mark_coords 1                # Mark first expression as coordinate'
        write(*,*) '    set linepoints 200           # Number of points along a line'
        write(*,*) '    midplane                     # Midplane profiles'
        write(*,*) '  done'
        write(*,*) ''
        write(*,*) 'All output is written into subfolder postproc/'
        write(*,*) ''
        write(*,*) 'Type "help" for general usage information or, e.g., "help average" for'
        write(*,*) 'command-specific help.'
        write(*,*) ''
        write(*,*) 'Documentation: http://jorek.eu/wiki/doku.php?id=jorek2_postproc'
      case ( 'average' )
        write(*,*) 'Usage:'
        write(*,*) '  average'
        write(*,*) ''
        write(*,*) 'Determine poloidally and toroidally averaged profiles.'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  set surfaces 200'
        write(*,*) '  expressions Psi_N rho T Er'
        write(*,*) '  mark_coords 1'
        write(*,*) '  for step 1 to 200'
        write(*,*) '    average'
        write(*,*) '  done'
      case ( 'average_h5' )
        write(*,*) 'Usage:'
        write(*,*) '  average_h5'
        write(*,*) ''
        write(*,*) 'Creates an "average" .h5 file from several ones.'
        write(*,*) ''
        write(*,*) 'The average of the absolute values of all variables'
        write(*,*) 'is written to a jorek99999.h5 file. The file can be'
        write(*,*) 'analyzed afterwards like any other .h5 restart file.'
        write(*,*) ''
        write(*,*) 'Note, that only the first degree of freedom is taken'
        write(*,*) 'into account, i.e., values at nodes. The other dofs'
        write(*,*) 'corresponding to s, t, and cross derivatives are set'
        write(*,*) 'to zero. Thus, the effective resolution is reduced.' 
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  for step 1 to 200'
        write(*,*) '    average_h5'
        write(*,*) '  done'
      case ( 'energy_spectrum' )
        write(*,*) 'Usage:'
        write(*,*) '  energy_spectrum tmin tmax'
        write(*,*) ''
        write(*,*) 'Output the energy spectrum in the given time window.'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  for step 200 do'
        write(*,*) '    energy_spectrum 150. 3000.'
        write(*,*) '  done'
      case ( 'equil_params' )
        write(*,*) 'Usage:'
        write(*,*) '  equil_params'
        write(*,*) ''
        write(*,*) 'Output equilibrim parameters (axis, X-point, limiter).'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  for step 1 to 200'
        write(*,*) '    equil_params'
        write(*,*) '  done'
      case ( 'exit' )
        write(*,*) 'Usage:'
        write(*,*) '  exit'
        write(*,*) '  quit'
        write(*,*) ''
        write(*,*) 'Stop the execution of jorek2_postproc.'
      case ( 'expressions' )
        write(*,*) 'Usage:'
        write(*,*) '  expressions [<expr1> <expr2> ...]'
        write(*,*) ''
        write(*,*) 'Parameters:'
        write(*,*) ' <expr1> etc        Short name of expression, e.g., Psi_N, T, rho, ...'
        write(*,*) ''
        write(*,*) 'Select physical expressions. Required by many commands. If called without'
        write(*,*) 'parameters, a table of available expressions is printed.'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  expressions'
        write(*,*) '  expressions Psi_N rho T Er'
      case ( 'expressions_int' )
        write(*,*) 'Usage:'
        write(*,*) '  expressions_int [<expr1> <expr2> ...]'
        write(*,*) ''
        write(*,*) 'Parameters:'
        write(*,*) ' <expr1> etc        Short name of expression, e.g., Wmag, ...'
        write(*,*) ''
        write(*,*) 'Select physical expressions. Required by int3d. If called without'
        write(*,*) 'parameters, a table of available expressions is printed.'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  expressions_int'
        write(*,*) '  expressions_int Wmag Thermal'
      case ( 'fluxsurfaces' ) 
        write(*,*) 'Usage:'
        write(*,*) '  fluxsurfaces'
        write(*,*) ''
        write(*,*) 'Output flux surfaces of the axisymmetric part of the field.'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  set surfaces 100'
        write(*,*) '  for step 100 do'
        write(*,*) '    fluxsurfaces'
        write(*,*) '  done'
        write(*,*) ''
      case ( 'for' ) 
        write(*,*) 'Usage:'
        write(*,*) '  for <time/step> <from> [to <to> [by <inc>]] do'
        write(*,*) '    ...'
        write(*,*) '  done'
        write(*,*) ''
        write(*,*) 'for step ... do'
        write(*,*) '  Execute one or several commands for one or several time-steps. If a time step'
        write(*,*) '  is not available, i.e., the restart file does not exist, it will be skipped.'
        write(*,*)
        write(*,*) 'for time ... do'
        write(*,*) '  Try to find for one or several simulations times corresponding time-steps and'
        write(*,*) '  executes one or several commands for these time-steps.'
        write(*,*) '  REMARK: Using option <to> requires to specify <inc> also.'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  for step 0 do                     # only for the single time step 0'
        write(*,*) '    ...'
        write(*,*) '  done'
        write(*,*) ''
        write(*,*) '  for step 0 to 200 do              # for all available time steps'
        write(*,*) '    ...                             # betweeen 0 and 200'
        write(*,*) '  done'
        write(*,*) ''
        write(*,*) '  for step 0 to 200 by 10 do        # for all available time steps'
        write(*,*) '    ...                             # 0, 10, 20, ... 200'
        write(*,*) '  done'
        write(*,*) ''
        write(*,*) '  for time 100. do                  # only for the single time step'
        write(*,*) '    ...                             # closest to time 100.0 '
        write(*,*) '  done'
        write(*,*) ''
        write(*,*) '  for time 100. to 200. by 10. do   # for the time steps closest to'
        write(*,*) '    ...                             # time 100.,110.,120. ... 200.'
        write(*,*) '  done'
        write(*,*) ''
      case ( 'four2d' ) 
        write(*,*) 'Usage:'
        write(*,*) '  four2d'
        write(*,*) ''
        write(*,*) 'Perform a 2D Fourier analysis in straight field line coordinats.'
        write(*,*) 'Creates a separate file for each time step and each m/n component.'
        write(*,*) ''
        write(*,*) 'Optional input parameters (set with command ''set parameter value''):'
        write(*,*) '- units: SI or JOREK units'
        write(*,*) '- surfaces: number of radial positions psi_N'
        write(*,*) '- rad_range_min: minimum psi_N (must be >0, eg 0.001)'
        write(*,*) '- rad_range_max: maximum psi_N (must be <1, eg 0.999)'
        write(*,*) '- nTht: number of points in theta* direction, must be >= 24*n_tor'
        write(*,*) '- deltaphi'
        write(*,*) '- nsmallsteps'
        write(*,*) '- nmaxsteps'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  set surfaces 100'
        write(*,*) '  set deltaphi 0.1'
        write(*,*) '  for step 100 do'
        write(*,*) '    four2d'
        write(*,*) '  done'
      case ( 'gourdon' ) 
        write(*,*) 'Usage:'
        write(*,*) '  gourdon R_min R_max n_R Z_min Z_max n_Z n_phi fact_phi fact_btor fact_bpol'
        write(*,*) ''
        write(*,*) 'Parameters:'
        write(*,*) '  R_min, R_max, n_R      Range along coordinate R and number of points'
        write(*,*) '  Z_min, Z_max, n_Z      Range along coordinate Z and number of points'
        write(*,*) '  n_phi                  Number of toroidal points'
        write(*,*) '  fact_phi               Transform phi coordinate by this factor (+1 or -1)'
        write(*,*) '  fact_btor              Transform B_tor by this factor (+1 or -1)'
        write(*,*) '  fact_bpol              Transform B_pol by this factor (+1 or -1)'
        write(*,*) ''
        write(*,*) 'Export the magnetic field for the Gourdon code.'
        write(*,*) ''
        write(*,*) 'The factors fact_phi, fact_btor, fact_bpol allow to transform to a different'
        write(*,*) 'coordinate system. Values should be 1 or -1 usually.'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  gourdon 1.2285 2.2035 200 -0.614 0.886 256 800 -1. -1. 1.'
      case ( 'grid' ) 
        write(*,*) 'Usage:'
        write(*,*) '  grid'
        write(*,*) ''
        write(*,*) 'Export the computational grid.'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  grid'
      case ( 'help' ) 
        write(*,*) 'Usage:'
        write(*,*) '  help [command]'
        write(*,*) ''
        write(*,*) '"help" Lists available commands. "help command" prints usage information'
        write(*,*) 'for the respective postprocessing command.'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  help'
        write(*,*) '  help point'
      case ( 'I_halo_TPF' ) 
        write(*,*) 'Usage:'
        write(*,*) '  I_halo_TPF'
        write(*,*) ''
        write(*,*) '"I_halo_TPF" exports the integral of the normal poloidal current '
        write(*,*) '(normal to the JOREK boundary). It is given in MA, defined as'
        write(*,*) ''
        write(*,*) '     I_halo(\phi) = 1/2 * \int |J_n| R dl  '           
        write(*,*) ''      
        write(*,*) '       I_halo[MA] = \int I_halo (\phi) d\phi  '
        write(*,*) ''
        write(*,*) 'I_halo(\phi) is also exported for each time if n_tor>1'
        write(*,*) 'The toroidal peaking factor TPF = max(I_halo(phi))/I_halo) is also given'
        write(*,*) 'See documentation in attched file in JIRA issue IMAS-2016'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  for step 0 to 100 do '
        write(*,*) '  I_halo_TPF'
        write(*,*) '  done'
      case ( 'int2d' ) 
        write(*,*) 'Usage:'
        write(*,*) '  int2d'
        write(*,*) ''
        write(*,*) '"int2d" calculates various 2d integrals (calls integrals.f90) and outputs'
        write(*,*) 'the results to file the file int2d_...'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  int2d'
      case ( 'int3d' ) 
        write(*,*) 'Usage:'
        write(*,*) '  int3d'
        write(*,*) ''
        write(*,*) '"int3d" calculates various 3d integrals and outputs'
        write(*,*) 'the results to file the file int3d_...'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  expressions_int Wmag Ohmic'
        write(*,*) '  int3d'
      case ( 'int_along_pol_line' )
        write(*,*) 'Usage:'
        write(*,*) '  int_along_pol_line R0 Z0 R1 Z1 phi'
        write(*,*) ''
        write(*,*) 'Integrate expressions along line from (R0,Z0,phi) to (R1,Z1,phi).'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  set linepoints 500'
        write(*,*) '  expressions R rho T E_r'
        write(*,*) '  mark_coords 1'
        write(*,*) '  for step 0 to 100 do'
        write(*,*) '    int_along_pol_line 1.6 0.5 1.7 0.5 0.'
        write(*,*) '  done'
      case ( 'jnorm_bnd_curr' ) 
        write(*,*) 'Usage:'
        write(*,*) '  jnorm_bnd_curr i_plane'
        write(*,*) ''
        write(*,*) '"jnorm_bnd_curr" calculates the normal current density to the jorek boundary'
        write(*,*) 'at the plane i_plane and exports it in a separate file for each time'
        write(*,*) ' the output format is Rbnd, Zbnd, Jnorm '
        write(*,*) ' '
        write(*,*) 'Examples:'
        write(*,*) '  jnorm_bnd_curr 1'
      case ( 'jorek-units' ) 
        write(*,*) 'Usage:'
        write(*,*) '  jorek-units'
        write(*,*) ''
        write(*,*) 'Switches to JOREK normalized units.'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  jorek-units'
        write(*,*) ''
        write(*,*) 'See also "help si-units"'
      case ( 'mark_coords' )
        write(*,*) 'Usage:'
        write(*,*) '  mark_coords n'
        write(*,*) ''
        write(*,*) 'Parameters:'
        write(*,*) '  n      Number of coordinate expressions'
        write(*,*) ''
        write(*,*) ''
        write(*,*) 'Mark the first n expressions as coordinates. Call this command after the'
        write(*,*) '"expressions" command. Marking coordinate expressions is required by some'
        write(*,*) 'commands like "four2d".'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  expressions Psi_N rho T Er'
        write(*,*) '  mark_coords 1'
      case ( 'midplane' )
        write(*,*) 'Usage:'
        write(*,*) '  midplane [inner|outer]'
        write(*,*) ''
        write(*,*) 'Output toroidally averaged midplane profiles. If no argument is provided,'
        write(*,*) 'both the hfs and lfs are included. The keywords "inner" and "outer" allow'
        write(*,*) 'to select one of the two.'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  set linepoints 200'
        write(*,*) '  for step 1 to 100 do'
        write(*,*) '    expressions R rho T Psi Er'
        write(*,*) '    mark_coords 1                    # mark first expression as coordinate'
        write(*,*) '    midplane outer                   # lfs only'
        write(*,*) '  done'
      case ( 'namelist' )
        write(*,*) 'Usage:'
        write(*,*) '  namelist input_file'
        write(*,*) ''
        write(*,*) 'Load namelist input file. Required by most commands.'
        write(*,*) ''
        write(*,*) 'Example:'
        write(*,*) '  namelist input1'
      case ( 'params' )
        write(*,*) 'Usage:'
        write(*,*) '  params'
        write(*,*) ''
        write(*,*) 'Output JOREK parameters (hardcoded and namelist input).'
        write(*,*) ''
      case ( 'point' )
        write(*,*) 'Usage:'
        write(*,*) '  point R Z [phi]'
        write(*,*) ''
        write(*,*) 'Determine the value of a variable at position (R,Z,phi).'
        write(*,*) 'If no value for phi is provided, expressions are toroidally averaged.'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  for step 1 to 100 do'
        write(*,*) '    expressions rho T Psi Er'
        write(*,*) '    point 1.6 0.0 0.0'
        write(*,*) '  done'
      case ( 'pol_line' )
        write(*,*) 'Usage:'
        write(*,*) '  pol_line R0 Z0 R1 Z1 phi'
        write(*,*) ''
        write(*,*) 'Expressions along line from (R0,Z0,phi) to (R1,Z1,phi).'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  set linepoints 500'
        write(*,*) '  expressions R rho T E_r'
        write(*,*) '  mark_coords 1'
        write(*,*) '  for step 0 to 100 do'
        write(*,*) '    pol_line 1.6 0.5 1.7 0.5 0.'
        write(*,*) '  done'
      case ( 'q_at_psin' )
        write(*,*) 'Usage:'
        write(*,*) '  q_at_psin Psi_N'
        write(*,*) ''
        write(*,*) 'Gives the value of the safety factor at given Psi_N over time'
        write(*,*) ''
        write(*,*) 'Example: (get q95 time trace)'
        write(*,*) '  for step 0 to 100 do'
        write(*,*) '    q_at_psin 0.95 '
        write(*,*) '  done'
      case ( 'separatrix' ) 
        write(*,*) 'Usage:'
        write(*,*) '  separatrix'
        write(*,*) ''
        write(*,*) 'Output the separatrix of the axisymmetric part of the field.'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  for step 100 do'
        write(*,*) '    separatrix'
        write(*,*) '  done'
        write(*,*) ''
      case ( 'set' )
        write(*,*) 'Usage:'
        write(*,*) '  set [name value]'
        write(*,*) ''
        write(*,*) 'Sets a setting to a certain value. Lists all settings if called'
        write(*,*) 'without parameters.'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  set linepoints 500     # used by pol_line, midplane, ...'
        write(*,*) '  set surfaces 200       # used by fluxsurfaces, average, ...'
        write(*,*) '  set                    # "set" lists all settings'
      case ( 'si-units' ) 
        write(*,*) 'Usage:'
        write(*,*) '  si-units'
        write(*,*) ''
        write(*,*) 'Switches to SI units.'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  si-units'
        write(*,*) ''
        write(*,*) 'See also "help jorek-units"'
      case ( 'spi-state' ) 
        write(*,*) 'Usage:'
        write(*,*) '  spi-state'
        write(*,*) ''
        write(*,*) 'Switches to SI units.'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  for step 0 to 100 do'
        write(*,*) '    spi-state'
        write(*,*) '  done'
      case ( 'timesteps' )
        write(*,*) 'Usage:'
        write(*,*) '  timesteps'
        write(*,*) ''
        write(*,*) 'Lists all available time steps (restart files).'
      case ( 'tor_line' )
        write(*,*) 'Usage:'
        write(*,*) '  tor_line R Z phi0 phi1'
        write(*,*) ''
        write(*,*) 'Expressions along line from (R,Z,phi0) to (R,Z,phi1).'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  set linepoints 500'
        write(*,*) '  expressions phi rho T E_r'
        write(*,*) '  mark_coords 1'
        write(*,*) '  for step 0 to 100 do'
        write(*,*) '    tor_line 1.6 0.1 0. 3.141592'
        write(*,*) '  done'
      case ( 'rectangle' )
        write(*,*) 'Usage:'
        write(*,*) '  rectangle Rmin Rmax nR Zmin Zmax nZ phi'
        write(*,*) ''
        write(*,*) 'Expressions on a rectangular area in R,Z. Produced an HDF5 file.'
        write(*,*) ''
        write(*,*) 'Examples:'
        write(*,*) '  expressions phi rho T E_r'
        write(*,*) '  for step 0 to 100 do'
        write(*,*) '    rectangle 1.7 2.1 10 -0.3 0.3 10 0.'
        write(*,*) '  done'
      case default
        write(*,*) '[This help topic does not exist, sorry]'
    end select
    write(*,*) '========================================================================='
    write(*,*) ''
    
  end subroutine specific_help
  
  
  
end module postproc_help
